services:
  app:
    build:
      dockerfile: Dockerfile
    image: classicaldft:local
    volumes:
      - ./include:/app/include
      - ./src:/app/src
      - ./tests:/app/tests
      - ./scripts:/app/scripts
      - ./build:/app/build
      - ./build-coverage:/app/build-coverage
      - ./coverage:/app/coverage
      - ./CMakeLists.txt:/app/CMakeLists.txt
      - ./.clang-format:/app/.clang-format
      - ./.clang-tidy:/app/.clang-tidy
