#!/usr/bin/env bash
set -e

source scripts/str_lib.sh

check() {
  message "info" "Check dependencies"

  if ! (command -v docker &>/dev/null); then
    message "error" "docker is not available"
    message "warning" "Install Docker: https://docs.docker.com/get-docker/"
    exit 1
  else
    message "success" "docker is available ($(docker --version))"
  fi

  if ! (command -v docker compose version &>/dev/null); then
    message "error" "docker compose is not available"
    exit 1
  else
    message "success" "docker compose is available ($(docker compose version))"
  fi
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  check "$@"
fi

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  check "$@"
fi
