#!/usr/bin/env bash
set -e

source scripts/str_lib.sh

DOCKER_IMAGE="${DOCKER_IMAGE:-classicaldft:dev}"

test() {
  message "info" "Tests (Docker)"

  docker build -t "$DOCKER_IMAGE" .
  message "success" "Docker image built"

  docker run --rm "$DOCKER_IMAGE"
  message "success" "Tests completed"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  test "$@"
fi
