name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE: classicaldft

jobs:
  commitlint:
    name: Commit lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v5

  test:
    name: Unit tests
    needs: [commitlint]
    runs-on: ubuntu-latest
    outputs:
      format: ${{ steps.format.outcome }}
      lint: ${{ steps.lint.outcome }}
      test: ${{ steps.test.outcome }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.DOCKER_IMAGE }}:local
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - id: format
        name: Code format checking
        run: ./scripts/format --check
      - id: lint
        name: Code linting
        run: ./scripts/lint
      - id: test
        name: Unit tests
        run: ./scripts/unit-tests
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  integration-tests:
    name: Integration tests
    needs: [test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.DOCKER_IMAGE }}:local
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Integration tests
        run: ./scripts/integration-tests
